title: Infektionsschutz
subtitle: Kompendium
author: Jakob Schumacher
description: > # this means to ignore newlines until "show_exerpts:"
  Infektionsschutzwissen von Gesundheitsämtern für Gesundheitsämter
show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

github: [metadata] # Fixing error of GitHub Metadata: No GitHub API authentication could be found. 

plainwhite:
  name: Jakob Schumacher
  tagline: Das Kompendium
  date_format: "%b %-d, %Y"
  sitemap: true # set to true to generate sitemap.xml content

  # generate social links in footer
  social_links:
    github:  jakobschumacher
    rss: rss

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - about.md

# Build settings
remote_theme: samarsault/plainwhite-jekyll

baseurl: "/infektionsschutzkompendium"

plugins:
  - jekyll-seo-tag
  - jekyll-last-modified-at
  - jekyll-include-cache

collections:
  fortbildung:
    output: true
  katalog:
    output: true
  querschnitt:
    output: true
  aktionen:
    output: true
